### ISSUE TITLE
ModuleNotFoundError: No module named 'pegasus.cli'

### ISSUE THREAD

**Issue by timsloan** [saaspegasus/pegasus-cli#14]
I installed pegasus-cli with `pip install "pegasus-cli[dev]"`  in my virtual env.

I'm on Windows WSL2, if that helps.

Here's the error:

```
$ pegasus --help
Traceback (most recent call last):
  File "/home/tim/virtualenvs/venv/bin/pegasus", line 5, in <module>
    from pegasus.cli import cli
ModuleNotFoundError: No module named 'pegasus.cli'
```

**Comment by czue** [comment]
eep, had my notifications set up wrong and only just saw this. let me look into it and report back asap

**Comment by czue** [comment]
hmm, not able to reproduce at first blush and wouldn't expect WSL to matter. what python are you using?

**Comment by timsloan** [comment]
I'm using 3.12. I _think_ it might be because there's an app in my project already called pegasus where the examples are. I can rename that on my project, but it's a default with Pegasus projects. It would make sense to rename one of them (and provide some instructions in the meantime).

**Comment by czue** [comment]
huh, that... makes a lot of sense! i'm now confused why it's working on my environments where i have a `pegasus` folder. i just tested on 3.12 and it's still working my side. i'll try a bit harder to reproduce on Monday and report back though.

**Comment by czue** [comment]
Can you try a few things for me:

1. Try with `python -m pegasus --help`
2. Try temporarily renaming the `pegasus` folder and running it again
3. Try running the following in a python shell and print the output:

```
>>> import pegasus
>>> print(pegasus.__file__)
>>> import pegasus.cli
>>> print(pegasus.cli.__file__)
```

**Comment by timsloan** [comment]
When the folder is "pegasus"

`python -m pegasus --help`
/usr/bin/python3.12: No module named pegasus.__main__; 'pegasus' is a package and cannot be directly executed

>>> import pegasus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pegasus'

If I rename the folder, the cli works. However, I still cannot import `pegasus`

**Comment by czue** [comment]
@timsloan can you `pip install pegasus-cli==0.5` and tell me if that fixes it?

**Comment by czue** [comment]
@timsloan any update on whether version 0.5 worked for you? I'm shipping a new pegasus release today or tomorrow and would be great to know if I've fixed this.

**Comment by timsloan** [comment]
@czue That works. I have a folder/module called `pegasus` and the cli works now.

**Comment by czue** [comment]
great! there's another issue with 0.5 that i'm working on now so you will probably have to upgrade to 0.6 soon
